version: "3"
services:
  db:
    image: postgres
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    ports:
    - database_port
    volumes: 
    - volume_path
  api:
    build: .
    ports:
      - api_port
    environment:
      - DATABASE_URL=postgresql://user:password@database_host:database_port/database_name
      - API_HOST=https://world.openfoodfacts.org
  metrics-dashboard:
    container_name: mycontainer
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mail
      PGADMIN_DEFAULT_PASSWORD: mail_password
    ports:
      - metrics-dashboard_port